### ISSUE TITLE
Updates to PMP home doc links

### ISSUE THREAD

**Issue by cavis** [PRX/pmp#6]
An upcoming release to the PMP will introduce some changes to home document links.  Changes have already been deployed to https://api-sandbox.pmp.io.  Here's my synopsis of what needs to happen for this SDK:

#### Breaking changes:
* `urn:collectiondoc:form:documentdelete` has been added, and the `DELETE` method removed from `urn:collectiondoc:form:documentsave`.  The only impact is that `PMP::CollectionDocument.delete` calls to `edit_link('DELETE')`, which would now raise an exception that the method isn't allowed.

#### Cleanup changes:
* regenerate fixtures
* `urn:collectiondoc:query:guids` should be removed from tests/fixtures
* `urn:collectiondoc:form:profilesave` should be removed from tests/fixtures
* `urn:collectiondoc:form:schemasave` should be removed from tests/fixtures

#### Possible upgrades:
* `urn:collectiondoc:form:listcredentials` has been added (use instead of hardcoding)
* use `urn:collectiondoc:form:issuetoken` and `urn:collectiondoc:form:revoketoken` instead of hardcoding the links

**Comment by kookster** [comment]
I believe with the merge of PR #7 we are all set, yes?

**Comment by cavis** [comment]
Right you are!
